/**
 * VisionX Real-Time AI Scene Intelligence Data Models & Constants
 */

export const PROJECT_MODES = {
  ROOM: 'ROOM',
  TRAFFIC: 'TRAFFIC',
  OBJECT: 'OBJECT'
};

export const EVENT_TYPES = {
  PERSON_ENTERED: 'PERSON_ENTERED',
  PERSON_LEFT: 'PERSON_LEFT',
  PERSON_TALKING_START: 'PERSON_TALKING_START',
  PERSON_TALKING_STOP: 'PERSON_TALKING_STOP',
  PERSON_SMILING: 'PERSON_SMILING',
  PERSON_DROWSY_ALERT: 'PERSON_DROWSY_ALERT',
  PERSON_SLEEPING_ALERT: 'PERSON_SLEEPING_ALERT',
  POSTURE_CHANGE: 'POSTURE_CHANGE',
  VEHICLE_SPEED_WARNING: 'VEHICLE_SPEED_WARNING',
  VEHICLE_DETECTED: 'VEHICLE_DETECTED'
};

export const STATUS_STATES = {
  TALKING: 'TALKING',
  SMILING: 'SMILING',
  MOVING: 'MOVING',
  STATIONARY: 'STATIONARY',
  DROWSY: 'DROWSY',
  SLEEPING: 'SLEEPING',
  SITTING: 'SITTING',
  STANDING: 'STANDING'
};
